train:
  seed: 42
  num_epochs: 10000
  batch_size_train: 8
  batch_size_val: 8
  checkpoint_dir: ${task.checkpoint_dir}
  eval_ckpt_name: "policy_last.ckpt"
  # eval_ckpt_name: "policy_epoch_6600_seed_42.ckpt"
